export const MENU_DATA = [{
	name: "网站首页",
	path: "/",
	subMenu: []
}, {
	name: "走进艾腾",
	path: "",
	subMenu: [{
		title: "服务项目",
		key: "subMenu_11",
		items: [{
			name: "网站建设一条龙",
			key: "subMenu_111",
			path: "/"
		}, {
			name: "网站建设一条龙",
			key: "subMenu_112",
			path: "/"
		}, {
			name: "网站建设一条龙",
			key: "subMenu_113",
			path: "/"
		}, {
			name: "网站建设一条龙",
			key: "subMenu_114",
			path: "/"
		}]
	}, {
		title: "服务项目",
		key: "subMenu_12",
		items: [{
			name: "网站建设一条龙",
			key: "subMenu_121",
			path: "/"
		}, {
			name: "网站建设一条龙",
			key: "subMenu_122",
			path: "/"
		}, {
			name: "网站建设一条龙",
			key: "subMenu_123",
			path: "/"
		}, {
			name: "网站建设一条龙",
			key: "subMenu_124",
			path: "/"
		}]
	}]
}, {
	name: "新闻动态",
	path: "服务项目",
	subMenu: [{
		title: "服务项目",
		key: "subMenu_21",
		items: [{
			name: "网站建设一条龙",
			key: "subMenu_211",
			path: "/"
		}, {
			name: "网站建设一条龙",
			key: "subMenu_212",
			path: "/"
		}, {
			name: "网站建设一条龙",
			key: "subMenu_213",
			path: "/"
		}, {
			name: "网站建设一条龙",
			key: "subMenu_214",
			path: "/"
		}]
	}, {
		title: "服务项目",
		key: "subMenu_22",
		items: [{
			name: "网站建设一条龙",
			key: "subMenu_221",
			path: "/"
		}, {
			name: "网站建设一条龙",
			key: "subMenu_222",
			path: "/"
		}, {
			name: "网站建设一条龙",
			key: "subMenu_223",
			path: "/"
		}, {
			name: "网站建设一条龙",
			key: "subMenu_224",
			path: "/"
		}]
	}]
}, {
	name: "客户案例",
	path: "",
	subMenu: [{
		title: "服务项目",
		key: "subMenu_31",
		items: [{
			name: "网站建设一条龙",
			key: "subMenu_311",
			path: "/"
		}, {
			name: "网站建设一条龙",
			key: "subMenu_312",
			path: "/"
		}, {
			name: "网站建设一条龙",
			key: "subMenu_313",
			path: "/"
		}, {
			name: "网站建设一条龙",
			key: "subMenu_314",
			path: "/"
		}]
	}]
}, {
	name: "服务范围",
	path: "",
	subMenu: [{
		title: "服务项目",
		key: "subMenu_41",
		items: [{
			name: "网站建设一条龙",
			key: "subMenu_411",
			path: "/"
		}, {
			name: "网站建设一条龙",
			key: "subMenu_412",
			path: "/"
		}, {
			name: "网站建设一条龙",
			key: "subMenu_413",
			path: "/"
		}, {
			name: "网站建设一条龙",
			key: "subMenu_414",
			path: "/"
		}]
	}, {
		title: "服务项目",
		key: "subMenu_42",
		items: [{
			name: "网站建设一条龙",
			key: "subMenu_421",
			path: "/"
		}, {
			name: "网站建设一条龙",
			key: "subMenu_422",
			path: "/"
		}, {
			name: "网站建设一条龙",
			key: "subMenu_423",
			path: "/"
		}, {
			name: "网站建设一条龙",
			key: "subMenu_424",
			path: "/"
		}]
	}]
}, {
	name: "解决方案",
	path: "",
	subMenu: [{
		title: "服务项目",
		key: "subMenu_51",
		items: [{
			name: "网站建设一条龙",
			key: "subMenu_511",
			path: "/"
		}, {
			name: "网站建设一条龙",
			key: "subMenu_512",
			path: "/"
		}, {
			name: "网站建设一条龙",
			key: "subMenu_513",
			path: "/"
		}, {
			name: "网站建设一条龙",
			key: "subMenu_514",
			path: "/"
		}]
	}, {
		title: "服务项目",
		key: "subMenu_52",
		items: [{
			name: "网站建设一条龙",
			key: "subMenu_521",
			path: "/"
		}, {
			name: "网站建设一条龙",
			key: "subMenu_522",
			path: "/"
		}, {
			name: "网站建设一条龙",
			key: "subMenu_523",
			path: "/"
		}, {
			name: "网站建设一条龙",
			key: "subMenu_524",
			path: "/"
		}]
	}]
}, {
	name: "移动应用",
	path: "服务项目",
	subMenu: [{
		title: "服务项目",
		key: "subMenu_61",
		items: [{
			name: "网站建设一条龙",
			key: "subMenu_611",
			path: "/"
		}, {
			name: "网站建设一条龙",
			key: "subMenu_612",
			path: "/"
		}, {
			name: "网站建设一条龙",
			key: "subMenu_613",
			path: "/"
		}, {
			name: "网站建设一条龙",
			key: "subMenu_614",
			path: "/"
		}]
	}, {
		title: "服务项目",
		key: "subMenu_62",
		items: [{
			name: "网站建设一条龙",
			key: "subMenu_621",
			path: "/"
		}, {
			name: "网站建设一条龙",
			key: "subMenu_622",
			path: "/"
		}, {
			name: "网站建设一条龙",
			key: "subMenu_623",
			path: "/"
		}, {
			name: "网站建设一条龙",
			key: "subMenu_624",
			path: "/"
		}]
	}]
}, {
	name: "联系我们",
	path: "",
	subMenu: [{
		title: "服务项目",
		key: "subMenu_71",
		items: [{
			name: "网站建设一条龙",
			key: "subMenu_711",
			path: "/"
		}, {
			name: "网站建设一条龙",
			key: "subMenu_712",
			path: "/"
		}, {
			name: "网站建设一条龙",
			key: "subMenu_713",
			path: "/"
		}, {
			name: "网站建设一条龙",
			key: "subMenu_714",
			path: "/"
		}]
	}, {
		title: "服务项目",
		key: "subMenu_72",
		items: [{
			name: "网站建设一条龙",
			key: "subMenu_721",
			path: "/"
		}, {
			name: "网站建设一条龙",
			key: "subMenu_722",
			path: "/"
		}, {
			name: "网站建设一条龙",
			key: "subMenu_723",
			path: "/"
		}, {
			name: "网站建设一条龙",
			key: "subMenu_724",
			path: "/"
		}]
	}]
}]